name: Build Flutter APK

on:
  # 1. UBAH BAGIAN INI: Tambahkan trigger saat ada Tag (v...)
  push:
    tags:
      - 'v*' # Contoh: v1.0, v1.0.1, dst.
  workflow_dispatch:

# 2. TAMBAHKAN INI: Izin supaya script bisa menulis di menu Releases
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK Release
        run: flutter build apk --release

      # Rename file agar sesuai keinginan Anda
      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-noteapp.apk

      # --- BAGIAN BARU: PUBLISH KE RELEASES ---
      - name: Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-noteapp.apk"
          token: ${{ secrets.GITHUB_TOKEN }} # Ini otomatis ada, tidak perlu disetting manual
          tag: ${{ github.ref_name }} # Mengambil nama tag (misal v1.0)
          name: "Release ${{ github.ref_name }}"
          body: "Ini adalah rilis otomatis dari GitHub Actions."
          generateReleaseNotes: true
      # ----------------------------------------